### ISSUE TITLE
Bill of materials

### ISSUE THREAD

**Issue by lucasuyezu** [mjohns/dactyl-cc#1]
Congrats on the project, this is awesome!

Could you add the Bill of Materials to the README?

Thanks!

**Comment by mjohns** [comment]
I added a link to the guide from the main readme. I just followed the qmk guide from the dactyl repo. https://github.com/adereth/dactyl-keyboard/tree/master/qmk-guide. I don't have a real bill or materials as a lot of the parts were left over from a dactyl build from a few years ago. 

That guide has a pretty good section about the materials that you would need. If you don't want to use a Teensy (and want to use pro micros) you could look at this guide https://nickgreen.info/dactyl-manuform-build-log/.
