### ISSUE TITLE
3D model filed corrupted

### ISSUE THREAD

**Issue by jiahuijiang** [mjohns/dactyl-cc#16]
I was trying to 3D print the base, but both v1 and v2 models are giving me warnings saying these are corrupted. Can you double check the files are uploaded correctly? Thank you!

<img width="392" alt="image" src="https://github.com/mjohns/dactyl-cc/assets/13910193/c019a425-d54a-43a4-acb8-8076027e7c1f">

**Comment by guategeek** [comment]
The files are not corrupted on github, I have a copy of the repo I have been going to print from. To double check I just test downloaded the left.stl and threw in in Cura no problem. How did you download the files?

<img width="782" alt="image" src="https://github.com/mjohns/dactyl-cc/assets/868801/cbf38790-a76c-4ab1-b9fd-c1327d26d6f7">

**Comment by jiahuijiang** [comment]
@guategeek good call!
When I right-clicked on the file name and tried to directly do "save link as", the model files was shown as corrupted. But If I clicked open the file in GitHub UI and then clicked "download", that worked.
Closing this ticket out.
