### ISSUE TITLE
Can't generate .STLs

### ISSUE THREAD

**Issue by dracc** [mjohns/dactyl-cc#18]
After compiling a fresh checkout of the repo using `build/build.sh`, I get no warnings/errors and the .scad files are generated.
Opening them in OpenSCAD 2024.03.08 (latest git HEAD at the time of writing) I get a few red faces in the thumb cluster: 
![image](https://github.com/mjohns/dactyl-cc/assets/1279635/04ce6589-024b-4341-80b2-4c665eefc91f)

<details><summary>When trying to render, I get stuck on step 96/1000 with a few CGAL errors in the log.</summary>

```
CGAL error in CGALUtils::applyUnion3D: CGAL ERROR: assertion violation!
Expr: G.mark(v1,0)==G.mark(v2,0)&& G.mark(v1,1)==G.mark(v2,1)
File: /usr/include/CGAL/Nef_S2/SM_overlayer.h
Line: 294
```
```
CGAL error in CGALUtils::applyUnion3D: CGAL ERROR: assertion violation!
Expr: itl != it->second.end()
File: /usr/include/CGAL/Nef_3/SNC_external_structure.h
Line: 1078
```
```
CGAL error in CGALUtils::applyUnion3D: CGAL ERROR: precondition violation!
Expr: ! _is_valid (_pred1_P) || comp_f (node2_P->object, _pred1_P->object) != SMALLER
File: /usr/include/CGAL/Multiset.h
Line: 2338
```
```
CGAL error in CGALUtils::applyUnion3D: CGAL ERROR: precondition violation!
Expr: ! _is_valid (_succ2_P) || comp_f (node1_P->object, _succ2_P->object) != LARGER
File: /usr/include/CGAL/Multiset.h
Line: 2343
```
```
CGAL error in CGALUtils::applyUnion3D: CGAL ERROR: assertion violation!
Expr: cet->get_index() == ce->twin()->get_index()
File: /usr/include/CGAL/Nef_3/SNC_external_structure.h
Line: 1145
```
A few of these show up multiple times.
</details>

Is there a known cause to this? Maybe even a fix? Or should I use the latest OpenSCAD release (2021.01) instead?

**Comment by rlowies** [comment]
I installed a fresh version of Ubuntu and I was able to get it to render, the same section did highlight but the STL rendered and I successfully loaded it into CURA.
This was with OpenSCAD version 2021.01

**Comment by dracc** [comment]
Thank you @rlowies!
After testing with 2021.01, it started working for me too.
