### ISSUE TITLE
Enough space for Amoebas?

### ISSUE THREAD

**Issue by simonjohansson** [mjohns/dactyl-cc#2]
Howdie. Cool alternative to the Dactyl!

You mention in the guide, 

```
This keyboard does not have as much room around the keys in the corners and edges
```

Do you think it has enough space for [Amoebas](https://keeb.io/collections/frontpage/products/amoeba-single-switch-pcbs?variant=12960782024798)?

**Comment by mjohns** [comment]
I updated the guide with an image of one in the tightest corner. It fits but I don't have any experience with them to say if that is enough. See https://github.com/mjohns/dactyl-cc/tree/master/guide

**Comment by simonjohansson** [comment]
Thanks!
