### ISSUE TITLE
Stabilizers for thumb cluster

### ISSUE THREAD

**Issue by daniel2887** [mjohns/dactyl-cc#7]
Hi,

I was looking for a split keyboard that replicated the keys and layout of the Kinesis Advantage 2 and this fit the bill perfectly, so thank you for sharing your work. I'm in the process of printing it! 🤞 

One question about the thumb cluster. I noticed there are no cutouts for stabilizers for the longer (2u?) keys. Did you tack those on somehow after the print? Or did you find they were not needed?

Thanks!

**Comment by mjohns** [comment]
I didn't use any stabilizers and it was fine for how I type. The advantage
also doesn't have stabilizers on those thumb keys.

**Comment by daniel2887** [comment]
Great. Thank you.
